# application.yml
# 공통 설정 파일로서 모든 환경에 공통으로 적용되는 범용적 설정을 포함합니다.
spring:
  jpa:
    hibernate:
      ddl-auto: update
      # JPA가 실행 시점에 DB 스키마를 자동 갱신합니다.
      # 개발 환경에서만 권장하며, 운영 환경에서는 수동 관리 권장.
    show-sql: true
    # 실행되는 SQL 쿼리를 콘솔에 출력해 디버깅을 지원합니다.

  profiles:
    active: dev
    # 기본 활성 프로파일을 개발(dev)로 설정합니다.

server:
  port: 8080
  # 서버 기본 포트 설정